name: Tests CI

on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image:  node:latest

    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn test
